server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
    register-with-eureka: false

ribbon:
  # 指的是建立连接后后从服务器读取到可用资源所用的时间，单位毫秒
  ReadTimeout: 5000
  # 指定的是建立连接所用的时间，是用于网络状况正常的情况下，两端连接所用的时间，单位毫秒
  ConnectTimeout: 5000

logging:
  level:
    # Feign日志以什么级别监控哪个接口
    com.hsuhau.springcloud.service.PaymentFeignService: debug