server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  zipkin:
    # docker run -d -p 9411:9411 openzipkin/zipkin
    base-url: http://192.168.116.134:9411
  sleuth:
    sampler:
      # 采样率值介于0到1之间，1则表示全部采集
      probability: 1
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.116.134:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  # 所有Entity别名类所在包
  type-aliases-package: com.hsuhau.springcloud.entities

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: payment8001
    # 访问路径显示IP地址
    prefer-ip-address: true
    # Eureka客户端向服务端法松心跳的时间间隔，单位为秒（默认是30秒）
    lease-renewal-interval-in-seconds: 1
    # Eureka服务端在收到最后一次心跳后等待时间上限。单位是秒（默认是90秒），超时将提出服务
    lease-expiration-duration-in-seconds: 2