server:
  port: 3344

spring:
  application:
    name: cloud-config-center # 注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hsuhau/cloud2020-config.git # GitHub上面的git仓库名字
          search-paths: # 搜索目录
            - cloud2020-config
          password: I211324>>just
          username: hsuhau
      label: master # 读取分支
  rabbitmq:
    host: 192.168.116.134
    port: 5672
    username: guest
    password: guest

# 服务注册到Eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka



# rabbitMQ相关配置，暴露Bus刷新配置的端点
management:
  endpoints: # 暴露Bus刷新配置的端点
    web:
      exposure:
        include: bus-refresh
