server:
  port: 80
spring:
  application:
    name: cloud-consumer-order
  cloud:
    # 注册到zookeeper地址
    zookeeper:
      connect-string: 192.168.116.139:2181,192.168.116.142:2182,192.168.116.140:2183