server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
          # payment_route 路由的ID，没有固定规则但要求唯一，建议配合服务名
        - id: payment_routh
          # 匹配后提供服务的路由地址
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          # 断言，路径相匹配的进行路由
          predicates:
            - Path=/payment/get/**

          # payment_route 路由的ID，没有固定规则但要求唯一，建议配合服务名
        - id: payment_routh2
          # 匹配后提供服务的路由地址
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          # 断言，路径相匹配的进行路由
          predicates:
            - Path=/payment/lb/**
#            - After=2020-06-13T02:55:27.779+08:00[Asia/Shanghai]
#            - Cookie=username,hsuhau
#            - Header=X-Request-Id, \d+
#            - Method=GET
      discovery:
        locator:
          enabled: true # 开启向注册中心创建动态路由的功能，利用微服务名进行路由
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
