server:
  port: 83

spring:
  application:
    name: nacos-order-cosumer
  cloud:
    nacos:
      discovery:
#        server-addr: localhost:8848
        # 换成Nginx的1111端口，做集群
        server-addr: 192.168.116.134:1111
service-url:
  nacos-user-service: http://nacos-payment-provider
