version: '3.3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root #设置root帐号密码
    ports:
      - 3306:3306
    volumes:
      - /cloud2020/mysql/data/db:/var/lib/mysql #数据文件挂载
      - /cloud2020/mysql/data/conf:/etc/mysql/conf.d #配置文件挂载
      - /cloud2020/mysql/log:/var/log/mysql #日志文件挂载

  nginx:
    image: nginx:1.10
    container_name: nginx_cloud2020
    volumes:
      - /cloud2020/nginx/nginx.conf:/etc/nginx/nginx.conf #配置文件挂载
      - /cloud2020/nginx/html:/usr/share/nginx/html #静态资源根目录挂载
      - /cloud2020/nginx/log:/var/log/nginx #日志文件挂载
    privileged:
      true
    ports:
      - 1111:1111
#  rabbitmq:
#    image: rabbitmq:3.7.15-management
#    container_name: rabbitmq
#    volumes:
#      - /cloud2020/rabbitmq/data:/var/lib/rabbitmq #数据文件挂载
#      - /cloud2020/rabbitmq/log:/var/log/rabbitmq #日志文件挂载
#    ports:
#      - 5672:5672
#      - 15672:15672
#
#  portainer:
#    image: portainer/portainer:latest
#    container_name: portainer
#    volumes:
#    - /var/run/docker.sock:/var/run/docker.sock
#    - /cloud2020/portainer/data:/data
#    ports:
#    - 9000:9000
#    - 8000:8000
#  jenkins:
#    image: jenkinsci/blueocean:latest
#    container_name: jenkins
#    volumes:
#    - /cloud2020/jenkins/data:/var/jenkins_home
#    - /var/run/docker.sock:/var/run/docker.sock
#    ports:
#    - 8080:8080
#    - 50000:50000