server:
  port: 8803
spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit: # 表示定义的名称，用于与binding整合
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: 192.168.116.134
                port: 5672
                username: guest
                password: guest
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称
          destination: studyExchange # 表示要使用的Exchange名称定义
          context-type: application/json # 设置消息类型，本次为JSON，文本则设置"text/plain"
          binder: defaultRabbit # 设置要绑定的消息服务的具体位置
#          group: B # 分组
          group: A # 分组

eureka:
  instance:
    hostname: cloud-stream-consumer
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了五秒的间隔
    lease-renewal-interval-in-seconds: 2 #设置心跳的时间间隔（默认是30秒）
    instance-id: receive8803 # 在信息列表时显示主机名称
    prefer-ip-address: true # 访问的路径变成IP地址
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
